export {
  applyTutorialLevelSetup,
  TASK_EXCAVATION_CENTER as TUTORIAL_EXCAVATION_TARGET,
  TASK_EXCAVATION_TARGET_COLOR_INDEX as TUTORIAL_EXCAVATION_TARGET_COLOR_INDEX,
  TASK_EXPLORATION_TARGETS as TUTORIAL_NAVIGATION_TARGETS,
  TUTORIAL_EXCAVATION_LAYERS,
  TUTORIAL_FACING_DIR_INDEX,
  TUTORIAL_START,
} from '../tasks/taskSandbox';