/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, CacheOnly } from 'workbox-strategies';
import { Queue } from 'workbox-background-sync';

// Use TypeScript's SVN of the window global in your service worker
declare const self: ServiceWorkerGlobalScope;

// Cleanup old caches
cleanupOutdatedCaches();

// Precache and route all files generated by your build process.
// They have hash names, so the urls are guaranteed to be unique per build.
let precacheManifest = self.__WB_MANIFEST || [];

// Remove files we don't want to precache
precacheManifest = precacheManifest.filter((entry) => {
  const entryUrl = typeof entry === 'string' ? entry : entry.url;
  return !entryUrl.match(/\/site\.webmanifest$/);
});

precacheAndRoute(precacheManifest);

// Handle all navigation requests using SPA strategy
const navigationHandler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(navigationHandler, {
  // Ignore URLs that start with these patterns
  denylist: [/^\/admin/, /^\/api/, /^\/sw\.js$/],
});
registerRoute(navigationRoute);

// Cache images and media with CacheFirst strategy
registerRoute(
  ({ request }) =>
    request.destination === 'image' ||
    request.destination === 'audio' ||
    request.destination === 'video',
  new CacheFirst({
    cacheName: 'assets-cache',
    plugins: [
      {
        handlerDidError: async () => {
          // Return a placeholder image on error if needed
          return new Response('', { status: 404 });
        },
      },
    ],
  })
);

// Cache CSS and JS with NetworkFirst strategy
registerRoute(
  ({ request }) =>
    request.destination === 'style' ||
    request.destination === 'script' ||
    request.destination === 'font',
  new NetworkFirst({
    cacheName: 'static-assets',
    networkTimeoutSeconds: 3,
  })
);

// Cache /manifest.json
registerRoute(
  ({ url }) => url.pathname === '/manifest.json',
  new CacheFirst({ cacheName: 'manifest-cache' })
);

// Handle background sync for failed requests (optional)
const bgSyncQueue = new Queue('hexigame-queue', {
  maxRetentionTime: 24 * 60, // Retry for max 24 hours
});

self.addEventListener('fetch', event => {
  // Only handle GET requests for now
  if (event.request.method !== 'GET') {
    return;
  }

  // Skip cross-origin requests
  if (!event.request.url.startsWith(self.location.origin)) {
    return;
  }
});

// Update notification on new version
self.addEventListener('message', async event => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
